import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';

// 常见的 .gitignore 模板
const TEMPLATES: Record<string, string[]> = {
  node: [
    '# Dependencies',
    'node_modules/',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    '',
    '# Build output',
    'dist/',
    'build/',
    'lib/',
    'esm/',
    'cjs/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '*~',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Logs',
    'logs/',
    '*.log',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    '',
    '# Cache',
    '.cache/',
    '.eslintcache',
    '.nyc_output/',
    'coverage/',
  ],
  react: [
    '# Dependencies',
    'node_modules/',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    '',
    '# Build output',
    'dist/',
    'build/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.development.local',
    '.env.test.local',
    '.env.production.local',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Testing',
    'coverage/',
    '.nyc_output/',
    '',
    '# Misc',
    '*.local',
  ],
  vue: [
    '# Dependencies',
    'node_modules/',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    '',
    '# Build output',
    'dist/',
    'lib/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Testing',
    'coverage/',
    '',
    '# Editor',
    '*.local',
  ],
  python: [
    '# Byte-compiled / optimized',
    '__pycache__/',
    '*.py[cod]',
    '*$py.class',
    '',
    '# Distribution',
    'build/',
    'dist/',
    '*.egg-info/',
    '*.egg',
    '',
    '# Virtual environments',
    'venv/',
    'env/',
    '.venv/',
    '.env/',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '.project',
    '.pydevproject',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Testing',
    '.pytest_cache/',
    '.coverage',
    'htmlcov/',
    '*.cover',
    '',
    '# Logs',
    '*.log',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
  ],
  java: [
    '# Compiled class file',
    '*.class',
    '',
    '# Log file',
    '*.log',
    '',
    '# Package Files',
    '*.jar',
    '*.war',
    '*.nar',
    '*.ear',
    '*.zip',
    '*.tar.gz',
    '*.rar',
    '',
    '# Maven',
    'target/',
    'pom.xml.tag',
    'pom.xml.releaseBackup',
    'pom.xml.versionsBackup',
    '',
    '# Gradle',
    'build/',
    '.gradle/',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.iml',
    '.settings/',
    '.classpath',
    '.project',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
  ],
  typescript: [
    '# Dependencies',
    'node_modules/',
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',
    '',
    '# Build output',
    'dist/',
    'build/',
    'lib/',
    'types/',
    '',
    '# TypeScript cache',
    '*.tsbuildinfo',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# Logs',
    'logs/',
    '*.log',
    'npm-debug.log*',
    '',
    '# Cache',
    '.cache/',
    '.eslintcache',
    '.turbo/',
  ],
  general: [
    '# Dependencies',
    'node_modules/',
    'vendor/',
    '',
    '# Build output',
    'dist/',
    'build/',
    'out/',
    '',
    '# Environment variables',
    '.env',
    '.env.local',
    '.env.*.local',
    '',
    '# IDE',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '*~',
    '',
    '# OS',
    '.DS_Store',
    'Thumbs.db',
    'desktop.ini',
    '',
    '# Logs',
    'logs/',
    '*.log',
    '',
    '# Cache',
    '.cache/',
    '',
    '# Temporary files',
    '*.tmp',
    '*.temp',
  ],
};

export async function gitignoreCommand(): Promise<void> {
  try {
    console.log(chalk.blue('📝 Gitignore 模板生成器'));
    console.log(chalk.gray('为当前项目生成 .gitignore 文件\n'));

    // 检查是否已存在 .gitignore
    const gitignorePath = path.join(process.cwd(), '.gitignore');
    if (fs.existsSync(gitignorePath)) {
      const { overwrite } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'overwrite',
          message: chalk.yellow('⚠️  .gitignore 文件已存在，是否覆盖？'),
          default: false,
        },
      ]);

      if (!overwrite) {
        console.log(chalk.yellow('操作已取消'));
        return;
      }
    }

    // 选择模板类型
    const { templateType } = await inquirer.prompt([
      {
        type: 'list',
        name: 'templateType',
        message: '选择项目类型:',
        choices: [
          { name: '🟢 Node.js 项目', value: 'node' },
          { name: '⚛️  React 项目', value: 'react' },
          { name: '💚 Vue 项目', value: 'vue' },
          { name: '🔵 Python 项目', value: 'python' },
          { name: '☕ Java 项目', value: 'java' },
          { name: '🔷 TypeScript 项目', value: 'typescript' },
          { name: '📦 通用模板', value: 'general' },
        ],
      },
    ]);

    // 获取模板内容
    const template = TEMPLATES[templateType];
    const templateContent = template.join('\n') + '\n';

    // 显示预览
    console.log(chalk.green('\n✓ 生成的 .gitignore 内容:'));
    console.log(chalk.gray('─'.repeat(50)));
    console.log(chalk.yellow(templateContent));
    console.log(chalk.gray('─'.repeat(50)));

    // 确认生成
    const { confirm } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'confirm',
        message: '是否生成 .gitignore 文件？',
        default: true,
      },
    ]);

    if (confirm) {
      // 写入文件
      fs.writeFileSync(gitignorePath, templateContent, 'utf8');
      console.log(chalk.green('\n✓ .gitignore 文件已成功创建！'));
      console.log(chalk.gray(`  路径: ${gitignorePath}`));
    } else {
      console.log(chalk.yellow('\n操作已取消'));
    }
  } catch (error: any) {
    console.error(chalk.red('❌ 生成失败:'), error.message);
    process.exit(1);
  }
}
